### ISSUE TITLE
Error: Cannot find module './.eslintrc.js'

### ISSUE THREAD

**Issue by haikalrios** [sellpixels/kit-react#2]
Hello everyone,

Node version: v12.18.0
yarn version  v1.22.0
I don't  no whats happen here. When I run yarn start after ran yarn install I recived this error 

$ react-app-rewired start
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module './.eslintrc.js'
Require stack:
- /xxxx/front-end/config-overrides.js
- /xxx/front-end/node_modules/react-app-rewired/config-overrides.js
- /xxxx/node_modules/react-app-rewired/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/xxxx/config-overrides.js:12:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/xxxx/config-overrides.js',
    '/xxxx/node_modules/react-app-rewired/config-overrides.js',
    '/xxxx/node_modules/react-app-rewired/scripts/start.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about

**Comment by haikalrios** [comment]
no

**Comment by haikalrios** [comment]
Thanks,  I get the project in this repository and extract ran yarn install and yarn start.
